//=============================================================================//
// This file is automatically generated. CHANGES WILL BE LOST.
//=============================================================================//
#include "cbase.h"
#include "srcpy.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

using namespace boost::python;

// The init method is in one of the generated files declared
#ifdef _WIN32
extern "C" __declspec(dllexport) PYINIT_DECL(unit_helper)();
extern "C" __declspec(dllexport) PYINIT_DECL(_editorsystem)();
extern "C" __declspec(dllexport) PYINIT_DECL(_achievements)();
extern "C" __declspec(dllexport) PYINIT_DECL(_steam)();
extern "C" __declspec(dllexport) PYINIT_DECL(_navmesh)();
extern "C" __declspec(dllexport) PYINIT_DECL(_recast)();
extern "C" __declspec(dllexport) PYINIT_DECL(_ndebugoverlay)();
extern "C" __declspec(dllexport) PYINIT_DECL(vprof)();
extern "C" __declspec(dllexport) PYINIT_DECL(_srctests)();
extern "C" __declspec(dllexport) PYINIT_DECL(matchmaking)();
#else
extern "C" PYINIT_DECL(unit_helper)();
extern "C" PYINIT_DECL(_editorsystem)();
extern "C" PYINIT_DECL(_achievements)();
extern "C" PYINIT_DECL(_steam)();
extern "C" PYINIT_DECL(_navmesh)();
extern "C" PYINIT_DECL(_recast)();
extern "C" PYINIT_DECL(_ndebugoverlay)();
extern "C" PYINIT_DECL(vprof)();
extern "C" PYINIT_DECL(_srctests)();
extern "C" PYINIT_DECL(matchmaking)();
#endif // _WIN32

// The append function
void AppendSharedModules()
{
	APPEND_MODULE(unit_helper)
	APPEND_MODULE(_editorsystem)
	APPEND_MODULE(_achievements)
	APPEND_MODULE(_steam)
	APPEND_MODULE(_navmesh)
	APPEND_MODULE(_recast)
	APPEND_MODULE(_ndebugoverlay)
	APPEND_MODULE(vprof)
	APPEND_MODULE(_srctests)
	APPEND_MODULE(matchmaking)
}
