//=============================================================================//
// This file is automatically generated. CHANGES WILL BE LOST.
//=============================================================================//
#include "cbase.h"
#include "srcpy.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

using namespace boost::python;

// The init method is in one of the generated files declared
#ifdef _WIN32
extern "C" __declspec(dllexport) PYINIT_DECL(_gameui)();
#else
extern "C" PYINIT_DECL(_gameui)();
#endif // _WIN32

// The append function
void AppendClientModules()
{
	APPEND_MODULE(_gameui)
}
